# Generated by Django 5.2.6 on 2025-09-19 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compounds', '0002_initial'),
        ('models', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReinventNetTraining',
            fields=[
                ('trainingstrategy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.trainingstrategy')),
                ('epochs', models.IntegerField(default=10)),
                ('batch_size', models.IntegerField(default=64)),
                ('learning_rate', models.FloatField(default=0.0001)),
            ],
            options={
                'verbose_name': 'Reinvent Training Strategy',
                'verbose_name_plural': 'Reinvent Training Strategies',
            },
            bases=('models.trainingstrategy',),
        ),
        migrations.CreateModel(
            name='ReinventNetValidation',
            fields=[
                ('validationstrategy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.validationstrategy')),
                ('validSetSize', models.IntegerField(default=10000)),
            ],
            options={
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('models.validationstrategy',),
        ),
        migrations.CreateModel(
            name='ReinventNet',
            fields=[
                ('model_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='models.model')),
                ('molset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='compounds.molset')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='genuireinvent.reinventnet')),
            ],
            options={
                'abstract': False,
            },
            bases=('models.model',),
        ),
    ]
