# Generated by Django 5.2.6 on 2025-09-21 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genuireinvent', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reinventnettraining',
            name='sample_batch_size',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='reinventnettraining',
            name='save_every_n_epochs',
            field=models.IntegerField(default=1),
        ),
    ]
