# Generated by Django 5.2.6 on 2025-10-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genuireinvent', '0002_reinventnettraining_sample_batch_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reinventnettraining',
            name='learning_rate',
        ),
    ]
