# Generated by Django 5.2.6 on 2025-10-17 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genuireinvent', '0003_remove_reinventnettraining_learning_rate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reinventnettraining',
            options={'base_manager_name': 'objects'},
        ),
    ]
