# Generated by Django 5.2.6 on 2025-10-29 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genuireinvent', '0004_alter_reinventnettraining_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reinventnetvalidation',
            name='random_seed',
            field=models.IntegerField(default=1337),
        ),
        migrations.AddField(
            model_name='reinventnetvalidation',
            name='split_method',
            field=models.CharField(default='random', max_length=16),
        ),
        migrations.AddField(
            model_name='reinventnetvalidation',
            name='temporal_cutoff',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='reinventnetvalidation',
            name='valid_fraction',
            field=models.FloatField(default=0.1),
        ),
    ]
