# Generated by Django 5.2.6 on 2025-10-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genuireinvent', '0005_reinventnetvalidation_random_seed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reinventnettraining',
            name='best_checkpoint_rel',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='reinventnettraining',
            name='best_epoch',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reinventnettraining',
            name='best_valid_nll',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
