# Generated by Django 5.2.6 on 2025-10-30 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genuireinvent', '0006_reinventnettraining_best_checkpoint_rel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reinventnettraining',
            name='best_checkpoint_rel',
        ),
        migrations.RemoveField(
            model_name='reinventnettraining',
            name='best_valid_nll',
        ),
        migrations.AddField(
            model_name='reinventnettraining',
            name='best_valid_loss',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
