# Generated by Django 5.2.6 on 2025-11-21 09:46

import django.db.models.deletion
import genui.generators.extensions.genuireinvent.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genuireinvent', '0007_remove_reinventnettraining_best_checkpoint_rel_and_more'),
        ('models', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReinventAgentTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_size', models.IntegerField(default=64)),
                ('unique_sequences', models.BooleanField(default=True)),
                ('randomize_smiles', models.BooleanField(default=True)),
                ('tb_isim', models.BooleanField(default=False)),
                ('use_checkpoint', models.BooleanField(default=False)),
                ('purge_memories', models.BooleanField(default=False)),
                ('summary_csv_prefix', models.CharField(default='reinvent', max_length=128)),
                ('learning_type', models.CharField(choices=genui.generators.extensions.genuireinvent.models.learning_strategy_choices, default='dap', max_length=32)),
                ('sigma', models.FloatField(default=128.0)),
                ('rate', models.FloatField(default=0.0001)),
            ],
        ),
        migrations.CreateModel(
            name='ReinventDiversityFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=genui.generators.extensions.genuireinvent.models.df_choices, max_length=128)),
                ('bucket_size', models.IntegerField(default=25)),
                ('minscore', models.FloatField(default=0.4)),
                ('minsimilarity', models.FloatField(default=0.4)),
                ('penalty_multiplier', models.FloatField(default=0.5)),
            ],
        ),
        migrations.CreateModel(
            name='ReinventEnvironmentScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aggregation_type', models.CharField(choices=[('geometric_mean', 'geometric_mean'), ('weighted_arithmetic_mean', 'weighted_arithmetic_mean')], max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ScoreModifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modifier_type', models.CharField(choices=[('ClippedScore', 'ClippedScore'), ('SmoothHump', 'SmoothHump')], max_length=32)),
                ('upper', models.FloatField(blank=True, null=True)),
                ('lower', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('low', models.FloatField(blank=True, null=True)),
                ('smooth', models.BooleanField(default=False)),
                ('sigma', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReinventAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.modelfile')),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='genuireinvent.reinventagenttraining')),
            ],
        ),
        migrations.CreateModel(
            name='ModelPerformanceReinvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('stage_index', models.IntegerField()),
                ('avg_score', models.FloatField(blank=True, null=True)),
                ('fraction_valid', models.FloatField(blank=True, null=True)),
                ('avg_nll', models.FloatField(blank=True, null=True)),
                ('unique_scaffolds', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genuireinvent.reinventagent')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='ReinventAgentValidation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validate_every', models.IntegerField(default=50)),
                ('validation_dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.modelfile')),
            ],
        ),
        migrations.AddField(
            model_name='reinventagent',
            name='validation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genuireinvent.reinventagentvalidation'),
        ),
        migrations.CreateModel(
            name='ReinventEnvironment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('inception_memory_size', models.IntegerField(default=0)),
                ('inception_sample_size', models.IntegerField(default=0)),
                ('agent_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reinvent_agent_files', to='models.modelfile')),
                ('diversity_filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genuireinvent.reinventdiversityfilter')),
                ('inception_smiles', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='models.modelfile')),
                ('prior_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reinvent_prior_files', to='models.modelfile')),
                ('reward_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genuireinvent.reinventenvironmentscores')),
            ],
        ),
        migrations.AddField(
            model_name='reinventagent',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='genuireinvent.reinventenvironment'),
        ),
        migrations.CreateModel(
            name='Reinvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tb_logdir', models.CharField(default='tb_logs', max_length=255)),
                ('json_out_config', models.CharField(default='_staged_learning.json', max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='genuireinvent.reinventagent')),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='genuireinvent.reinventenvironment')),
            ],
        ),
        migrations.CreateModel(
            name='ReinventStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('termination_type', models.CharField(default='simple', max_length=64)),
                ('max_score', models.FloatField(default=1.0)),
                ('min_steps', models.IntegerField(default=1)),
                ('max_steps', models.IntegerField(default=100)),
                ('scoring_source', models.CharField(choices=[('inline', 'Inline'), ('file', 'File')], default='inline', max_length=16)),
                ('chkpt_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reinvent_stage_checkpoints', to='models.modelfile')),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='genuireinvent.reinvent')),
                ('scoring_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reinvent_stage_scoring_files', to='models.modelfile')),
                ('scoring_scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genuireinvent.reinventenvironmentscores')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PropertyScorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.FloatField(default=1.0)),
                ('property_name', models.CharField(max_length=64)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='genuireinvent.reinventenvironmentscores')),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genuireinvent.scoremodifier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GenUIModelScorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.FloatField(default=1.0)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='models.model')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='genuireinvent.reinventenvironmentscores')),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genuireinvent.scoremodifier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnwantedSmartsScorer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weight', models.FloatField(default=1.0)),
                ('enabled', models.BooleanField(default=True)),
                ('modifier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='genuireinvent.scoremodifier')),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='genuireinvent.reinventenvironmentscores')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
