run_type = "transfer_learning"
device = "cpu"
tb_logdir = "/Users/artemfadeev/diplom/genui/files/media_debug/models/tb_TL_5"

[parameters]
num_epochs = 2
save_every_n_epochs = 1
batch_size = 16
sample_batch_size = 100

input_model_file = "/Users/artemfadeev/diplom/genui/files/checkpoints/prior/reinvent.prior"
smiles_file = "/Users/artemfadeev/diplom/genui/files/media_debug/models/ReinventNet5_project6_804ee47860e4433da8b1bab2c55e2fd2_aux.smi"
validation_smiles_file = "/Users/artemfadeev/diplom/genui/files/media_debug/models/ReinventNet5_project6_7b7bdbb192e247fba691b0b90e5fe1f7_aux.smi"
output_model_file = "/Users/artemfadeev/diplom/genui/files/media_debug/models/ReinventNet5_project6_4c517cf5ff23485ea268d1dde3d6a6b1_aux.model"
