run_type = "transfer_learning"
device = "cpu"
tb_logdir = "/Users/artemfadeev/diplom/genui/files/media_debug/models/tb_TL_1"

[parameters]
num_epochs = 2
save_every_n_epochs = 1
batch_size = 16
sample_batch_size = 100

input_model_file = "/Users/artemfadeev/diplom/genui/files/checkpoints/prior/reinvent.prior"
smiles_file = "/Users/artemfadeev/diplom/genui/files/media_debug/models/ReinventNet1_project2_587126bc26754c73b20a578cd263395f_aux.smi"
validation_smiles_file = "/Users/artemfadeev/diplom/genui/files/media_debug/models/ReinventNet1_project2_c412f36928324bea8a93737290e812f9_aux.smi"
output_model_file = "/Users/artemfadeev/diplom/genui/files/media_debug/models/ReinventNet1_project2_62e2406ebfbc41c0a052b203658067a8_aux.model"
